### ISSUE TITLE
Lỗi 

### ISSUE THREAD

**Issue by leanbinh** [Aetherya/TFT-Token-Farmer#1]
mình bị gặp lỗi ấn ok và để im chuột vẫn không có gì xảy ra :V 
![image](https://user-images.githubusercontent.com/67872108/86991043-4dbbe180-c1c8-11ea-9212-0227d53ae178.png)
Bot started, queuing up!
Traceback (most recent call last):
  File "aki tfttokenfarmer.py", line 154, in <module>
    queue()
  File "aki tfttokenfarmer.py", line 61, in queue
    if onscreen("./captures/tft logo.png"):
  File "aki tfttokenfarmer.py", line 20, in onscreen
    return search(path, precision)[0] != -1
  File "C:\Users\leanb\AppData\Local\Programs\Python\Python38-32\lib\site-packages\python_imagesearch\imagesearch.py", line 122, in imagesearch
    template.shape[::-1]
AttributeError: 'NoneType' object has no attribute 'shape

**Comment by h3x4n1um** [comment]
> 
> 
> mình bị gặp lỗi ấn ok và để im chuột vẫn không có gì xảy ra :V
> ![image](https://user-images.githubusercontent.com/67872108/86991043-4dbbe180-c1c8-11ea-9212-0227d53ae178.png)
> Bot started, queuing up!
> Traceback (most recent call last):
> File "aki tfttokenfarmer.py", line 154, in
> queue()
> File "aki tfttokenfarmer.py", line 61, in queue
> if onscreen("./captures/tft logo.png"):
> File "aki tfttokenfarmer.py", line 20, in onscreen
> return search(path, precision)[0] != -1
> File "C:\Users\leanb\AppData\Local\Programs\Python\Python38-32\lib\site-packages\python_imagesearch\imagesearch.py", line 122, in imagesearch
> template.shape[::-1]
> AttributeError: 'NoneType' object has no attribute 'shape

Source code thiếu ảnh ở `./captures` ông ạ =]]

**Comment by Aetherya** [comment]
Đã fix :D không hiểu sao upload thiếu mà cũng hông để ý luôn xD
